import { StyleSheet, Dimensions } from 'react-native'

var width = Dimensions.get('window').width; //full width
var height = Dimensions.get('window').height;

const Style = StyleSheet.create({
    Container: {
        flex: 1,
    },
    ViewModal: {
        position: "absolute",
        zIndex: 2,
        height: height,
        width: width,
        justifyContent: "center",
        alignItems: "center",
    },
    ModalInfo: {
        width: '100%',
        height: '90%',
        shadowColor: "#000",
        position: "relative",
        shadowOffset: {
            width: 1,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ViewIconMenu: {
        width: 50,
        height: 50,
        top: 40,
        paddingTop: 10,
        backgroundColor: "#222",
        borderRadius: 100,
        shadowColor: "#000",
        position: "absolute",
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        alignItems: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ViewIconNiple: {
        width: 50,
        height: 50,
        top: 50,
        right: 25,
        paddingTop: 10,
        borderRadius: 100,
        backgroundColor: "#FFFFFF",
        shadowColor: "#000",
        position: "absolute",
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        alignItems: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ViewBadge: {
        position: "absolute",
        height: 25,
        width: 25,
        right: -5,
        top: -5,
        backgroundColor: "#FF0000",
        paddingTop: 2,
        shadowColor: "#000",
        borderRadius: 100,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        alignItems: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    TextBadge: {
        fontWeight: "bold",
        fontSize: 17,
        color: "#FFF",
    },
    ViewWarningVehicles: {
        height: 65,
        width: '95%',
        top: 40,
        opacity: 0.8,
        zIndex: 2,
        position: "absolute",
        backgroundColor: "#FFFFFF",
        shadowColor: "#000",
        borderRadius: 10,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        alignItems: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ViewInWarning: {
        width: 100,
        height: 40,
        marginTop: 15,
        marginRight: 10,
        padding: 10,
        justifyContent: "center",
        backgroundColor: "#FF0000",
        shadowColor: "#000",
        borderRadius: 10,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        alignItems: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    ViewNotification: {
        height: 65,
        width: '95%',
        left: 10,
        zIndex: 5,
        padding: 10,
        flexDirection: "column",
        position: "absolute",
        backgroundColor: "#faee64",
        shadowColor: "#000",
        borderRadius: 10,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    TextBoardNotification: {
        fontWeight: "bold",
        color: "#222",
        fontSize: 20,
    },
    TextInfoNotification: {
        marginTop: 2,
        color: "#222",
        fontSize: 15,
    },
    ViewPolyline: {
        height: 65,
        width: '95%',
        left: 10,
        zIndex: 5,
        padding: 10,
        flexDirection: "column",
        position: "absolute",
        backgroundColor: "#FFFFFF",
        opacity: 0.8,
        shadowColor: "#000",
        borderRadius: 10,
        shadowOffset: {
            width: 1,
            height: 2,
        },
        alignSelf: "center",
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    }
})

export default Style